ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS province_code VARCHAR(10),
  ADD COLUMN IF NOT EXISTS province_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS city_code VARCHAR(10),
  ADD COLUMN IF NOT EXISTS city_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS barangay_code VARCHAR(10),
  ADD COLUMN IF NOT EXISTS barangay_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS purok VARCHAR(100),
  ADD COLUMN IF NOT EXISTS street VARCHAR(200),
  ADD COLUMN IF NOT EXISTS house_no VARCHAR(50),
  ADD COLUMN IF NOT EXISTS landmark VARCHAR(200);
